parameters:
    locale_fallback: en

    # One of `legacy` (default) or `solr`
    search_engine: '%env(SEARCH_ENGINE)%'

    ## Session handler, by default set to file based (instead of ~) in order to be able to use %ezplatform.session.save_path%
    ezplatform.session.handler_id: session.handler.native_file

    # Session save path as used by symfony session handlers (eg. used for dsn with redis)
    ezplatform.session.save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

    # Settings for Cache pool, to change add own cache service and optionally inject own arguments
    # predefined pools: see symfony config and the optional pools in app/config/cache_pool/
    # @todo fix this comment
    cache_pool: '%env(CACHE_POOL)%'

    # By default cache ttl is set to 24h, when using Varnish you can set a much higher value. High values depends on
    # using EzSystemsPlatformHttpCacheBundle (default as of v1.12) which by design expires affected cache on changes
    httpcache_default_ttl: '%env(HTTPCACHE_DEFAULT_TTL)%'

    # Settings for HttpCache
    purge_server: '%env(HTTPCACHE_PURGE_SERVER)%'

    ## Purge type used by HttpCache system ("local", "varnish"/"http", and on ee also "fastly")
    purge_type: local

    # Varnish invalidation/purge token (for use on platform.sh, eZ Platform Cloud and other places you can't use IP for ACL)
    # varnish_invalidate_token: '%env(HTTPCACHE_VARNISH_INVALIDATE_TOKEN)%' # @todo option is not available for some reason

    ezpublish_rest.csrf_token_intention: authenticate

    # Top menu parameters
    app.top_menu.parent_location_id: 2
    app.top_menu.included_content_type_identifier: ["folder", "inspiration_list"]

    # Location Ids of allowed user groups for viewing Articles with premium content
    # 12 - members, 13 administrator_users, 14 - editors
    app.premium_content.allowed_user_groups.location_ids: [12, 13, 14]

    app.migration_reference_file: '/src/MigrationVersions/References/references.yml'

    app.migration.values_mapping:
        app.home.place_list_location_id: 'ref_location_place_list__home__places_and_tastes__places'
        app.home.tastes_location_id: 'ref_location_folder__home__places_and_tastes__tastes'
        ezsettings.default.app_subscribe_location_id: 'ref_location_subscribe__home__subscribe'

    # e-mail address used for form submission
    app.contact_form.sender_email: no-reply@ez.no

    # e-mail address used as a message recipient
    app.contact_form.recipient_email: no-reply@ez.no

    eztags.default.tag_view.pagelayout: '@@ezdesign/pagelayout.html.twig'
    eztags.default.tag_view.template: '@@NetgenTags/tag/view.html.twig'

ezplatform:
    # HttpCache settings, By default 'local' (Symfony HttpCache Proxy), by setting it to 'http' you can point it to Varnish
    http_cache:
        purge_type: '%purge_type%'

    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: '%search_engine%'
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list:
            - site
            - admin
            - fr
            - de
            - no
        groups:
            site_group:
                - site
                - fr
                - de
                - no
            # WARNING: Do not remove or rename this group.
            # It's used to distinguish common siteaccesses from admin ones.
            # In case of multisite with multiple admin panels, remember to add any additional admin siteaccess to this group.
            admin_group: [admin]
        default_siteaccess: site
        match:
            URIElement: 1

    # System settings, read in following order: `default`, <siteaccess-group>, <siteacces>, and `global`
    # TIP: For multisite installations organize shared config into SiteAccess groups,
    #      on single-site you can place shared config under "default" for simplicity as shown below.
    system:
        default:
            # Cache pool service, needs to be different per repository (database) on multi repository install.
            cache_service_name: '%cache_pool%'
            # These reflect the current installers, complete installation before you change them. For changing var_dir
            # it is recommended to install clean, then change setting before you start adding binary content, otherwise you'll
            # need to manually modify your database data to reflect this to avoid exceptions.
            var_dir: var/site
            content:
                # As we by default enable EzSystemsPlatformHttpCacheBundle which is designed to expire all affected cache
                # on changes, and as error / redirects now have separate ttl, we easier allow ttl to be greatly increased
                default_ttl: '%httpcache_default_ttl%'
            # HttpCache purge server(s) setting, eg Varnish, for when ezpublish.http_cache.purge_type is set to 'http'.
            http_cache:
                purge_servers: ['%purge_server%']
                # varnish_invalidate_token: '%varnish_invalidate_token%' # @todo enable ezplatform-http-cache first

        site_group:
            design: main

        admin_group:
            # System languages. Note that by default, content, content types, and other data are in eng-GB locale,
            # so removing eng-GB from this list may lead to errors or content not being shown, unless you change
            # all eng-GB data to other locales first.
            # For admin this needs to contain all languages you want to translate content to on the given repository.
            languages: [eng-GB, fre-FR, ger-DE, nor-NO]
            design: admin
            content_tree_module:
                contextual_tree_root_location_ids:
                    - 2 # Home (Content structure)
                    - 5 # Users
                    - 43 # Media
                    - 48 # Setup
            subtree_paths:
                content: /1/2/
                media: /1/43/

        site:
            languages: [eng-GB, fre-FR, ger-DE, nor-NO]

        fr:
            languages: [fre-FR, eng-GB]

        de:
            languages: [ger-DE, eng-GB]

        no:
            languages: [nor-NO, eng-GB]

    url_alias:
        slug_converter:
            transformation: 'urlalias_lowercase'
ezdesign:
    design_list:
        main: [tastefulplanet]
        admin: [admin, tastefulplanet]

ez_platform_standard_design:
    # makes Kernel default templates (in EzPublishCoreBundle/Resources/views) part of standard Design
    override_kernel_templates: false

framework:
    translator: { fallback: '%locale_fallback%' }
    validation: { enable_annotations: true }
    default_locale: '%locale_fallback%'
    esi: true
    fragments: true
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        # if handler_id set to null will use default session handler from php.ini
        handler_id: '%ezplatform.session.handler_id%'
        save_path: '%ezplatform.session.save_path%'
        # Note: eZ Platform also allows session name and session cookie configuration to be per SiteAccess, by
        #       default session name will be set to "eZSESSID{siteaccess_hash}" (unique session name per siteaccess)
        #       Further reading on sessions: http://doc.ezplatform.com/en/latest/guide/sessions/
    http_method_override: true
    cache:
        pools:
            cache.array:
                adapter: cache.adapter.array
                default_lifetime: 3600
                public: true
                tags: true

#nova_ezseo:
#    system:
#        default:
#            #custom_fallback_service: ezstudiodemo.seo.fallback
#            default_links:
#                Index:
#                    href: { location_id: 2 }
#                    title: "Home"
##                Search:
##                    href: { route: "ezpublish_ezstudiodemo_search" }
##                    title: "Search"
##                "Shortcut icon":
##                    href: { asset: "/bundles/ezstudiodemo/images/favicon.ico" }
##                    type: "image/x-icon"
#            default_metas:
#                author: "eZ Systems"
#                copyright: "eZ Systems"
#                generator: "eZ Platform"
#                MSSmartTagsPreventParsing: ~
#            fieldtype_metas:
#                title:
#                    label: "Title"
#                    default_pattern: "<title|short_title|name>"
#                description:
#                    label: "Description"
#                    default_pattern: "<description|short_description|intro|title|name>"
#                keywords:
#                    label: "Keywords"
#                    default_pattern: "<tags>"
#                canonical:
#                    label: "External Canonical URL"
#                    default_pattern: ~
#                    icon: "link"
#                "og:title":
#                    label: "Facebook - Title"
#                    default_pattern: "<title|short_title|name>"
#                    icon: "facebook-official"
#                "og:description":
#                    label: "Facebook - Description"
#                    default_pattern: "<short_description|description|intro|title|name>"
#                    icon: "facebook-official"
#                "og:image":
#                    label: "Facebook - Image"
#                    default_pattern: "<image|picture>"
#                    icon: "facebook-official"
#                "twitter:title":
#                    label: "Twitter - Title"
#                    default_pattern: "<title|short_title|name>"
#                    icon: "twitter-square"
#                "twitter:description":
#                    label: "Twitter - Description"
#                    default_pattern: "<short_description|description|intro|title|name>"
#                    icon: "twitter-square"
#                "twitter:image":
#                    label: "Twitter - Image"
#                    default_pattern: "<image|picture>"
#                    icon: "twitter-square"
