login:
    path: /login
    defaults: { _controller: ezpublish.security.controller:loginAction }

login_check:
    path: /login_check

logout:
    path: /logout

kernel.internal:
    resource: '@EzPublishCoreBundle/Resources/config/routing/internal.yml'

kernel.rest:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: /api/ezp/v2

ezplatform.admin_ui:
    resource: '@EzPlatformAdminUiBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

_ezplatformRepositoryFormsRoutes:
    resource: '@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml'

fos.js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

_eztagsRoutes:
    resource: "@NetgenTagsBundle/Resources/config/routing.yml"

_novaezseoRoutes:
    resource: "@NovaeZSEOBundle/Controller/"
    type:     annotation
    prefix:   /

app.submitted:
    path: /contact/submitted
    defaults:
        _controller: app.controller.contactform:submittedAction
        template: "@ezdesign/full/contact_form_submitted.html.twig"
    methods: [GET]
